#!/bin/bash

read -r -d '' usage << EOT
USAGE
  bootstrap

DESCRIPTION
  Initializes development and test databases with owner.
EOT

bootstrap() {
  if [[ $1 == "-h" || $1 == "--help" ]]; then
    echo "$usage"
    exit 0
  fi

  if [[ ! -f $(which psql) ]]; then
    echo "Unable to locate psql. Please ensure you have postgres installed."
    exit 0
  fi

  if [[ -z "$PG_HOST" ]]; then
    PG_HOST="localhost"
  fi

  if [[ -z "$PG_USER" ]]; then
    PG_USER=$(whoami)
  fi

  echo "PG_HOST: $PG_HOST    PG_USER: $PG_USER"

  psql -h "$PG_HOST" -U "$PG_USER" -d template1 << SQL
CREATE USER caelid WITH PASSWORD 'radahn';
CREATE DATABASE caelid_development WITH owner = 'caelid';
CREATE DATABASE caelid_test WITH owner = 'caelid';
SQL
}
