refresh_rate: 30 seconds

appenders:
  stdout_ap:
    kind: console
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S)} | {h({l})} | {M}] {m}{n}"

  requests_ap:
    kind: rolling_file
    path: "logs/requests.log"
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S)} | {h({l})}] {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 50 mb
      roller:
        kind: fixed_window
        pattern: logs/requests/requests_{}.gz
        count: 5
        base: 1

root:
  level: debug
  appenders:
    - stdout_ap

loggers:
  actix_server:
    level: warn
    appenders:
      - stdout_ap
    additive: false

  caelid::app::server::middleware::request_info:
    level: info
    appenders:
      - requests_ap
    additive: true

  globset:
    level: warn
    appenders:
      - stdout_ap
    additive: false
